### ISSUE TITLE
io.py

### ISSUE THREAD

**Issue by Jojinionn** [RescueRobotProject/Tashy-RPi#3]
入力出力

**Comment by U-one831** [comment]
input  outputの関数を提供
pythonのinput機能でユーザーからのを受け取る
その時は文字列だから値（整数）に変える（pythonにそういう関数がある）
変えれないときは0とする
inputを2回呼び出して（整数）変数とする
plus関数から1つの値（整数）が返されるそれをoutput
outputは1つの引き数
print関数で出力

**Comment by Jojinionn** [comment]
input output
input受け取る　ユーザ　　inputで整数保証
文字列を整数に変換できないなら０
output
引数を整数
pythonのprint関数で表示
返す必要はない

**Comment by U-one831** [comment]
サンタさんはio.pyを担当

**Comment by Jojinionn** [comment]
io1.py

**Comment by U-one831** [comment]
input で　入力されたのを受け取る2つ
それをmain関数に返す

output はmain関数からきたのを受けってprintする
